### ISSUE TITLE
requests

### ISSUE THREAD

**Issue by IanHawke** [jupyter/ngcm-tutorial#15]
The `requests` library is mentioned twice: once on day 3 (download images), and once on day 1 (nbconvert as a library). Should I add this to the `conda install` list on the website (and update the README), or are we not expecting to cover those lessons?

**Comment by Carreau** [comment]
`requests` is pretty standard, I think if they want to play with network resources it would be nice to have requests.

**Comment by IanHawke** [comment]
I'll update the webpage; PR for the README in a sec.

**Comment by Carreau** [comment]
I've updated the readme.

**Comment by IanHawke** [comment]
Thanks!
