### ISSUE TITLE
Dead link in Numerical Chaos exercise

### ISSUE THREAD

**Issue by maxalbert** [jupyter/ngcm-tutorial#20]
The link to the "very nice presentation" in the [Numerical Chaos Exercise](https://github.com/jupyter/ngcm-tutorial/blob/master/Day-1/exercises/NumericalChaos.ipynb) is dead. I found [these slides](http://code.google.com/p/python-turtle-demo/downloads/detail?name=SevenWaysToUseTurtle-PyCon2009.pdf) of a presentation from PyCon 2009 about the turtle module. Is that the one you mean? I couldn't find a video, unfortunately.

**Comment by fperez** [comment]
Yes, that was it... Thanks! I'll fix it now, thanks for catching the dead link...

**Comment by fperez** [comment]
Just fixed it, sorry I forgot to add a proper "Closes #20" to the commit message....
